CREATE DATABASE ESEED  ; 
CREATE TABLE EMPLOYEE(
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(100) , 
EMAIL VARCHAR(100) UNIQE, 
MOBILENUMBER VARCHAR(50), 
HIREDATE DATE
) ; 

CREATE TABLE USER(
ID INT PRIMARY KEY AUTO_INCREMENT,
NAEE VARCHAR(100),
EMAIL VARCHAR(100) UNIQE,
PASSWORD VARCHAR(100)
) ; 

CREATE TABLE STATUS(
INT ID PRIMARY KEY AUTO_INCREMENT, 
TYPE VARCHAR(50) UNIQE
);

CREATE TABLE ATTENDANCE(
ID INT PRIMARY KEY AUTO AUTO_INCREMENT,
DAY DATE, 
WORKINGHOURS INT, 
EMPLOYEE_ID INT REFERENCES EMPLOYEE(ID),
STATUS_ID INT REFERENCES STATUS(ID)
) ;